# Generated by Django 5.2.8 on 2025-11-28 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aboutpage_body_alter_aboutpage_image_caption_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Grande image plein écran affichée en haut de la page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de fond du hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_kicker',
            field=models.CharField(blank=True, default='Bienvenue', help_text="Ex : 'Agence digitale · Exemple Wagtail'", max_length=150, verbose_name='Petit texte au-dessus du titre'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Sous-titre de présentation pour la page d’accueil.', help_text='Quelques phrases qui expliquent le site.', verbose_name='Texte sous le titre'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='Titre de la page d’accueil', help_text="Ex : 'Créez un site vitrine moderne, clair et efficace.'", max_length=200, verbose_name='Titre principal'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image_caption',
            field=models.CharField(blank=True, default='', max_length=225, verbose_name='Légende de l’image'),
        ),
    ]
